<?php
    class Variables{
        public $eu_countries = array(
            'Austria',
            'Belgium',
            'Czech Republic',
            'Denmark',
            'Estonia',
            'Finland',
            'France',
            'Germany',
            'Greece',
            'Hungary',
            'Iceland',
            'Italy',
            'Latvia',
            'Liechtenstein',
            'Lithuania',
            'Luxemberg',
            'Malta',
            'Netherlands',
            'Poland',
            'Portugal',
            'Slovakia',
            'Slovenia',
            'Spain',
            'Sweden',        
            'Switzerland',
        );
        public $normal_countries = array(
            'Afghanistan',
            'Albania',
            'Algeria',
            'American Sam',
            'Andorra',
            'Angola',
            'Anguilla',
            'Antigua And Barbuda',
            'Argentina',
            'Armenia',
            'Aruba',
            'Australia',
            'Azerbaijan',
            'Bahamas',
            'Bahrain',
            'Banladesh',
            'Barbados',
            'Belarus',
            'Belize',
            'Benin',
            'Bermuda',
            'Bhutan',
            'Bolivia',
            'Bosnia',
            'Botswana',
            'Brazil',
            'Brunie Daruss.',
            'Bulgaria',
            'Burkina Faso',
            'Burundi',
            'Cambodia',
            'Cameroon',
            'Canada',
            'Cape Verde',
            'Camayan Islands',
            'Central African Republic',
            'Chad',
            'Channel Islands',
            'Chile',
            'China',
            'Christmas Islands',
            'Cocos Keeling Isl',
            'Colombia',
            'Comoros',
            'Congo',
            'Cook Islands',
            'Costa Rica',
            'Croatia',
            'Cuba',
            'Cyprus',
            'Czechia',
            'Djibouti',
            'Dominica',
            'Dominican Republic',
            'East Timor',
            'Ecuador',
            'Egypt',
            'El Salvador',
            'Equatorial Guin',
            'Eritrea',
            'Ethiopia',
            'Falkand Islands',
            'Faroe Islands',
            'Fiji',
            'French Polynesia',
            'French Southern Ter',
            'Gabon',
            'Gambia',
            'Georgia',
            'Ghana',
            'Gibraltar',
            'Greenland',
            'Grenada',
            'Guadeloupe',
            'Guam',
            'Guatemala',
            'Guinea',
            'Guinea Bissau',
            'Guyana',
            'Haiti',
            'Honduras',
            'Hong Kong',
            'India',
            'Indonesia',
            'Iran',
            'Iraq',
            'Ireland',
            'Israel',
            'Israel',
            'Ivory Coast',
            'Jamaica',
            'Japan',
            'Jordan',
            'Kazakhstan',
            'Kenya',
            'Kiribati',
            'Kosovo',
            'Kuwait',
            'Krygyzstan',
            'Laos',
            'Lebanon',
            'Lesotho',
            'Liberia',
            'Libyan Arab Jamahiriya',
            'Macau',
            'Macedonia',
            'Madagascar',
            'Malawi',
            'Malaysia',
            'Maldives', 
            'Mali',
            'Marshall Islands',
            'Martinique',
            'Mauritanina',
            'Mauritius',
            'Mayotte',
            'Mexico',
            'Micronesia',
            'Moldova',
            'Monaco',
            'Mongolia',
            'Montenegro',
            'Montserrat',
            'Morocco',
            'Mozambique',
            'Myanmar',
            'Namibia',
            'Nauro',
            'Nepal',
            'Netherlands Antilles',
            'New Caledonina',
            'New Zealand',
            'Nicaragua',
            'Niger',
            'Nigeria',
            'Niue',
            'Norfolk Island',
            'Northern Mariana Isl',
            'Norway',
            'Oman',
            'Pakistan',
            'Palau',
            'Palestine',
            'Panama',
            'Papua New Guinea',
            'Paraguay',
            'Peru',
            'Philippines',
            'Pitcairn',
            'Puerto Rico',
            'Qatar',
            'Reunion',
            'Romania',
            'Russian Federation',
            'Rwanda',
            'Saint Barthelemy',
            'Saint Lucia',
            'Saint Vincent And The Grenadines',
            'Samoa',
            'San Marino',
            'Saudi Arabia',
            'Scotland',
            'Senegal',
            'Serbia',
            'Seychelles',
            'Sierra Leone',
            'Singapore',
            'Solomon Islands',
            'Somalia',
            'South Africa',
            'South Korea',
            'Sri Lanka',
            'Sthelina',
            'Sudan',
            'Suriname',
            'Swaziland',
            'Syrian Arab Republic',
            'São Tomé And Príncipe',
            'Taiwan',
            'Tajikistan',
            'Tanzania',
            'Thailand',
            'Togo',
            'Tokelau',
            'Tonga',
            'Trinidad And Tobago',
            'Tunisia',
            'Turkey',
            'Turkmenistan',
            'Tuvalu',
            'USA',
            'US Minor Outlying Isl',
            'Uganda',
            'Ukraine',
            'United Arab Emirates',
            'United Kingdom',
            'Uruguay',
            'Uzbekistan',
            'Vanuatu',
            'Vatican City St.',
            'Wallis Futuna Islands',
            'Western Sahara',
            'Yemen',
            'Zaire',
            'Zambia',
            'Zimbabwe'
        );
        public $educations = array(
            "Primary School",
            "Secondary School",
            "College",
            "Vocational School",
            "Bachelors Degree",
            "Masters Degree",
            "Other"
        );
        public $months = array(
            'January',
            'February',
            'March',
            'April',
            'May',
            'June',
            'July',
            'August',
            'September',
            'October',
            'November',
            'December'
        );
        public $nationalities = array(
            'Afghan',
            'Albanian',
            'Algerian',
            'American',
            'Andorran',
            'Angolan',
            'Anguillan',
            'Argentine',
            'Armenian',
            'Australian',
            'Austrian',
            'Azerbaijani',
            'Bahamian',
            'Bahraini',
            'Bangladeshi',
            'Barbadian',
            'Belarusian',
            'Belgian',
            'Belizean',
            'Beninese',
            'Bermudian',
            'Bhutanese',
            'Bolivian',
            'Botswanan',
            'Brazilian',
            'British',
            'British Virgin Islander',
            'Bruneian',
            'Bulgarian',
            'Burkinan',
            'Burmese',
            'Burundian',
            'Cambodian',
            'Cameroonian',
            'Canadian',
            'Cape Verdean',
            'Cayman Islander',
            'Central African',
            'Chadian',
            'Chilean',
            'Chinese',
            'Citizen Of Antigua And Barbuda',
            'Citizen Of Bosnia And Herzegovina',
            'Citizen Of Guinea Bissau',
            'Citizen Of Kiribati',
            'Citizen Of Seychelles',
            'Citizen Of The Dominican Republic',
            'Citizen Of Vanuatu',
            'Colombian',
            'Comoran',
            'Congolese',
            'Cook Islander',
            'Costa Rican',
            'Croatian',
            'Cuban',
            'Cymraes',
            'Cymro',
            'Cypriot',
            'Czech',
            'Danish',
            'Djiboutian',
            'Dominican',
            'Dutch',
            'East Timorese',
            'Ecuadorean',
            'Egyptian',
            'Emirati',
            'English',
            'Equatorial Euinean',
            'Eritrean',
            'Estonian',
            'Ethiopian',
            'Faroese',
            'Fijian',
            'Filipino',
            'Finnish',
            'French',
            'Gabonese',
            'Gambian',
            'Georgian',
            'German',
            'Ghanaian',
            'Gibraltarian',
            'Greek',
            'Greenlandic',
            'Grenadian',
            'Guamanian',
            'Guatemalan',
            'Guinean',
            'Guyanese',
            'Haitian',
            'Honduran',
            'Hong Konger',
            'Hungarian',
            'Icelandic',
            'Indian',
            'Indonesian',
            'Iranian',
            'Iraqi',
            'Irish',
            'Israeli',
            'Italian',
            'Ivorian',
            'Jamaican',
            'Japanese',
            'Jordanian',
            'Kazakh',
            'Kenyan',
            'Kittitian',
            'Kosovan',
            'Kuwaiti',
            'Kyrgyz',
            'Lao',
            'Latvian',
            'Lebanese',
            'Liberian',
            'Libyan',
            'Liechtenstein Citizen',
            'Lithuanian',
            'Luxembourger',
            'Macanese',
            'Macedonian',
            'Malagasy',
            'Malawian',
            'Malaysian',
            'Maldivian',
            'Malian',
            'Maltese',
            'Marshallese',
            'Martiniquais',
            'Mauritanian',
            'Mauritian',
            'Mexican',
            'Micronesian',
            'Moldovan',
            'Monegasque',
            'Mongolian',
            'Montenegrin',
            'Montserratian',
            'Moroccan',
            'Mosotho',
            'Mozambican',
            'Namibian',
            'Nauruan',
            'Nepalese',
            'New Zealander',
            'Nicaraguan',
            'Nigerian',
            'Niuean',
            'North Korean',
            'Northern Irish',
            'Norwegian',
            'Omani',
            'Pakistani',
            'Palauan',
            'Palestinian',
            'Panamanian',
            'Papua New Guinean',
            'Paraguayan',
            'Peruvian',
            'Pitcairn Islander',
            'Polish',
            'Portuguese',
            'Prydeinig',
            'Puerto Rican',
            'Qatari',
            'Romanian',
            'Russian',
            'Rwandan',
            'Salvadorean',
            'Sammarinese',
            'Samoan',
            'Sao Tomean',
            'Saudi Arabian',
            'Scottish',
            'Senegalese',
            'Serbian',
            'Sierra Leonean',
            'Singaporean',
            'Slovak',
            'Slovenian',
            'Solomon Islander',
            'Somali',
            'South African',
            'South Korean',
            'South Sudanese',
            'Spanish',
            'Sri Lankan',
            'St Helenian',
            'St Lucian',
            'Stateless',
            'Sudanese',
            'Surinamese',
            'Swazi',
            'Swedish',
            'Swiss',
            'Syrian',
            'Taiwanese',
            'Tajik',
            'Tanzanian',
            'Thai',
            'Togolese',
            'Tongan',
            'Trinidadian',
            'Tristanian',
            'Tunisian',
            'Turkish',
            'Turkmen',
            'Turks And Caicos Islander',
            'Tuvaluan',
            'Ugandan',
            'Ukrainian',
            'Uruguayan',
            'Uzbek',
            'Vatican Citizen',
            'Venezuelan',
            'Vietnamese',
            'Vincentian',
            'Wallisian',
            'Welsh',
            'Yemen',
            'Zambian',
            'Zimbabwean'
        );
        #https://en.wikipedia.org/wiki/List_of_official_languages
        public $languages = array(
            'Afar',
            'Afrikaans',
            'Aja-Gbe',
            'Akan',
            'Albanian',
            'Amharic',    
            'Anii',
            'Arabic',
            'Armenian',   
            'Assamese',
            'Aymara',
            'Azerbaijani',
            'Balanta',
            'Bambara',
            'Bariba',
            'Basque',
            'Bassari',
            'Bedik',
            'Belarusian',
            'Bengali',
            'Berber',
            'Biali',
            'Bislama',
            'Boko',
            'Bomu',
            'Bosnian',
            'Bozo',
            'Buduma',
            'Bulgarian',
            'Burmese',
            'Cantonese',
            'Catalan',
            'Chinese, Mandarin',
            'Chichewa',
            'Chirbawe',
            'Comorian',
            'Croatian',
            'Czech',
            'Dagaare',
            'Dagbani',
            'Dangme',
            'Danish',
            'Dari',
            'Dendi',
            'Dhivehi',
            'Dioula',   
            'Dogon',
            'Dutch',
            'Dzongkha',
            'English',
            'Estonian',
            'Ewe-Gbe',
            'Fijian',
            'Filipino',
            'Finnish',
            'Fon-Gbe',
            'Foodo',
            'Formosan',
            'French',
            'Fula:',
            'Ga',
            'Gàidhlig',
            'Gbe',
            'Gen-Gbe',
            'Georgian',
            'German',
            'Gonja',
            'Gourmanché',
            'Greek',
            'Guaraní',
            'Gujarati',
            'Haitian Creole',
            'Hakka',
            'Hassaniya',
            'Hausa',
            'Hebrew',
            'Hindi',
            'Hiri Motu',
            'Hungarian',
            'Igbo',
            'Icelandic',
            'Indonesian',
            'Irish',   
            'Italian',
            'Japanese',
            'Javanese',
            'Jola',
            'Kabye',
            'Kalanga',
            'Kannada',
            'Kanuri',
            'Kasem',
            'Kazakh',
            'Khmer',
            'Kinyarwanda',
            'Kirundi',
            'Kissi',
            'Khoisan',
            'Korean',
            'Korean Sign Language',
            'Kpelle',
            'Kurdish',
            'Kyrgyz',
            'Lao',
            'Latvian',
            'Lithuanian',
            'Lukpa',
            'Luxembourgish',
            'Macedonian',
            'Malagasy',
            'Malay',
            'Malinke',
            'Maltese',
            'Mamara',
            'Manding',
            'Mandinka',
            'Mandjak',
            'Mankanya',
            'Manx Gaelic',
            'Māori',   
            'Marshallese',
            'Mbelime',
            'Moldovan',
            'Mongolian',
            'Montenegrin',
            'Mossi',
            'Nambya',
            'Nateni',
            'Nauruan',
            'Ndau',
            'Ndebele',
            'Ndebele',
            'Nepali',
            'New Zealand Sign Language',
            'Noon',
            'Northern Sotho',
            'Norwegian',
            'Nzema',
            'Oniyan',
            'Oromo',
            'Ossetian',
            'Palauan',
            'Papiamento',
            'Pashto',
            'Persian',
            'Polish',
            'Portuguese',
            'Punjabi',
            'Quechua',
            'Romanian',
            'Romansh',
            'Russian',
            'Safen',
            'Samoa',
            'Sango',
            'Sena',
            'Scots',   
            'Serbian',
            'Serer',
            'Seychellois Creole',
            'Shona',
            'Sinhala',
            'Slovak',
            'Slovene',
            'Somali',
            'Songhay-Zarma',
            'Soninke',
            'Sotho',
            'Spanish',
            'Susu',
            'Swahili',
            'Swati',
            'Swedish',
            'Syenara',
            'Taiwan Sign Languag',
            'Taiwanese Hokkien',
            'Tajik',
            'Tagalog',
            'Tamasheq',
            'Tamil',
            'Tammari',
            'Tasawaq',
            'Tebu',
            'Telugu',
            'Tetum',
            'Thai',
            'Tigrinya',
            'Tok Pisin',
            'Toma',
            'Tonga',
            'Tongan',
            'Tsonga',
            'Tswana',
            'Turkish',   
            'Turkmen',
            'Tuvaluan',
            'Ukrainian',
            'Urdu',
            'Uzbek',
            'Venda',
            'Vietnamese',
            'Waama',
            'Waci-Gbe',
            'Wamey',
            'Welsh',
            'Wolof',
            'Xhosa',
            'Xwela-Gbe',
            'Yobe',
            'Yom',
            'Yoruba',
            'Zimbabwean sign language',
            'Zulu'
        );
        public $religions = array(
            'No Religion',
            'Buddhist',
            'Christian',
            'Catholic',
            'Brotestant',
            'Baptist',
            'Hindu',
            'Jewish',
            'Muslim',
            'Sikh',
            'Jain',
            'Other'
        );
        #https://www.worlddata.info/currencies/
        public $currencies = array(
            'AED',
            'AFN',
            'ALL',
            'AMD',
            'ANG',
            'AOA',
            'ARS',
            'AUD',
            'AWG',
            'AZN',
            'BAM',
            'BBD',
            'BDT',
            'BGN',
            'BHD',
            'BIF',
            'BMD',
            'BND',
            'BOB',
            'BRL',
            'BSD',
            'BTN',
            'BWP',
            'BYR',
            'BZD',
            'CAD',
            'CDF',
            'CHF',
            'CKD',
            'CLP',
            'CNY',
            'COP',
            'CRC',
            'CUP',
            'CVE',
            'CZK',
            'DJF',
            'DKK',
            'DOP',
            'DZD',
            'EGP',
            'ERN',
            'ETB',
            'EUR',
            'FJD',
            'FKP',
            'FOK',
            'GBP',
            'GEL',
            'GGP',
            'GHS',
            'GIP',
            'GMD',
            'GNF',
            'GTQ',
            'GYD',
            'HKD',
            'HNL',
            'HRK',
            'HTG',
            'HUF',
            'IDR',
            'ILS',
            'IMP',
            'INR',
            'IQD',
            'IRR',
            'ISK',
            'JEP',
            'JMD',
            'JOD',
            'JPY',
            'KES',
            'KGS',
            'KHR',
            'KID',
            'KMF',
            'KPW',
            'KRW',
            'KWD',
            'KYD',
            'KZT',
            'LAK',
            'LBP',
            'LKR',
            'LRD',
            'LSL',
            'LYD',
            'MAD',
            'MDL',
            'MGA',
            'MKD',
            'MMK',
            'MNT',
            'MOP',
            'MRO',
            'MUR',
            'MVR',
            'MWK',
            'MXN',
            'MYR',
            'MZN',
            'NAD',
            'NGN',
            'NIO',
            'NOK',
            'NPR',
            'NZD',
            'OMR',
            'PAB',
            'PEN',
            'PGK',
            'PHP',
            'PKR',
            'PLN',
            'PYG',
            'QAR',
            'RON',
            'RSD',
            'RUB',
            'RWF',
            'SAR',
            'SBD',
            'SCR',
            'SDG',
            'SEK',
            'SGD',
            'SHP',
            'SLL',
            'SOS',
            'SRD',
            'SSP',
            'STD',
            'SYP',
            'SZL',
            'THB',
            'TJS',
            'TMT',
            'TND',
            'TOP',
            'TRY',
            'TTD',
            'TVD',
            'TWD',
            'TZS',
            'UAH',
            'UGX',
            'USD',
            'UYU',
            'UZS',
            'VEF',
            'VND',
            'VUV',
            'WST',
            'XAF',
            'XCD',
            'XOF',
            'XPF',
            'YER',
            'ZAR',
            'ZMW',
            'ZWL'
        ); 
    }

?>